version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: veterinaria
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_veterinaria
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: veterinaria@clinica.com
      PGADMIN_DEFAULT_PASSWORD: veterinaria
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db

networks:
  pg-network:
